
// 通配符权限
const WILDCARD_PERMISSIONS = [
  'tshock.*',
  'tshock.rest.*',
  'tshock.world.*',
  'tshock.admin.*',
  'tshock.command.*',
];

export const TSHOCK_PERMISSIONS = {
  rest: [
    'tshock.rest.bans.manage',
    'tshock.rest.bans.view',
    'tshock.rest.groups.manage',
    'tshock.rest.groups.view',
    'tshock.rest.kick',
    'tshock.rest.mute',
    'tshock.rest.kill',
    'tshock.rest.broadcast',
    'tshock.rest.command',
    'tshock.rest.cfg',
    'tshock.rest.maintenance',
    'tshock.rest.users.manage',
    'tshock.rest.users.view',
    'tshock.rest.users.info',
    'tshock.rest.butcher',
    'tshock.rest.causeevents',
  ],
  general: [
    'tshock.admin',
    'tshock.admin.noban',
    'tshock.admin.nokick',
    'tshock.admin.nomute',
    'tshock.admin.permanentban',
    'tshock.admin.tempban',
    'tshock.world.editspawn',
    'tshock.world.movenpc',
    'tshock.world.time.dawn',
    'tshock.world.time.dusk',
    'tshock.world.time.fullmoon',
    'tshock.world.time.midnight',
    'tshock.world.time.noon',
    'tshock.world.time.set',
    'tshock.world.toggleexpert',
    'tshock.world.toggleparty',
    'tshock.world.togglepvp',
    'tshock.world.transferteam',
    'tshock.world.butcher',
    'tshock.world.butcher.hostile',
    'tshock.world.butcher.friendly',
    'tshock.world.butcher.bosses',
    'tshock.godmode',
    'tshock.godmode.other',
    'tshock.heal',
    'tshock.heal.other',
    'tshock.invincible',
    'tshock.invincible.other',
    'tshock.immunebuff',
    'tshock.immunebuff.other',
    'tshock.npc.buff',
    'tshock.npc.spawnboss',
    'tshock.npc.spawnmob',
    'tshock.npc.givename',
    'tshock.npc.look',
    'tshock.npc.remove',
    'tshock.npc.maxspawns',
    'tshock.npc.spawnrate',
    'tshock.spawn',
    'tshock.spawn.other',
    'tshock.warp',
    'tshock.warp.allowhide',
    'tshock.warp.create',
    'tshock.warp.delete',
    'tshock.warp.hidden',
    'tshock.warp.list',
    'tshock.warp.other',
    'tshock.warp.send',
    'tshock.warp.tp',
    'tshock.home',
    'tshock.home.set',
    'tshock.home.allowmultiple',
    'tshock.home.teleport',
    'tshock.tp',
    'tshock.tp.here',
    'tshock.tp.overrideblocked',
    'tshock.tp.pos',
    'tshock.tp.silent',
    'tshock.tp.others',
    'tshock.item.spawn',
    'tshock.item.give',
    'tshock.item.give.allowstack',
    'tshock.ignore.ssc',
    'tshock.chest',
    'tshock.chest.allowstart',
    'tshock.chest.info',
    'tshock.chest.log',
    'tshock.chest.protect',
    'tshock.chest.protect.nostack',
    'tshock.chest.removeprotection',
    'tshock.chest.viewinventory',
    'tshock.chest.allowall',
    'tshock.sawpvp',
    'tshock.sawparty',
    'tshock.say',
    'tshock.say.color',
    'tshock.saylogs',
    'tshock.whisper',
    'tshock.whisper.color',
    'tshock.whisper.log',
    'tshock.superadmin',
    'tshock.annoy',
    'tshock.antispam.exempt',
    'tshock.ban',
    'tshock.ban.view',
    'tshock.kick',
    'tshock.mute',
    'tshock.log.clear',
    'tshock.log.read',
    'tshock.timeban',
    'tshock.timeban.view',
    'tshock.summon',
    'tshock.summon.allowall',
    'tshock.admin.viewtiles',
    'tshock.essentials',
    'tshock.essentials.firework',
    'tshock.essentials.roll',
    'tshock.essentials.clear',
    'tshock.essentials.sudo',
    'tshock.motd',
    'tshock.motd.allowcolor',
    'tshock.motd.admin',
    'tshock.rules',
    'tshock.rules.allowcolor',
    'tshock.rules.admin',
    'tshock.time',
    'tshock.region',
    'tshock.region.setowner',
    'tshock.region.allowz',
    'tshock.region.allowadminuse',
    'tshock.region.adminuser',
    'tshock.region.delete',
    'tshock.region.define',
    'tshock.region.flag.own',
    'tshock.region.flag.other',
    'tshock.region.info',
    'tshock.region.list',
    'tshock.region.own',
    'tshock.region.user',
    'tshock.send',
    'tshock.projectile',
    'tshock.spectate',
    'tshock.spectate.other',
    'tshock.removetile',
    'tshock.removetile.quick',
    'tshock.paint',
    'tshock.tilerow',
    'tshock.tilewall',
    'tshock.tilewall.quick',
    'tshock.give.item.byid',
    'tshock.give.item.byname',
    'tshock.give.buff.byid',
    'tshock.give.buff.byname',
    'tshock.command.help',
    'tshock.command.info',
    'tshock.command.rules',
    'tshock.command.motd',
    'tshock.command.who',
    'tshock.command.me',
    'tshock.command.party',
    'tshock.command.hug',
    'tshock.command.shake',
    'tshock.command.slap',
    'tshock.command.point',
    'tshock.command.grow',
    'tshock.command.tell',
    'tshock.command.reply',
    'tshock.command.r',
    'tshock.command.p',
    'tshock.command.rocket',
    'tshock.command.angry',
    'tshock.command.laugh',
    'tshock.command.cry',
    'tshock.command.taunt',
    'tshock.command.kill',
    'tshock.command.puke',
    'tshock.command.confused',
    'tshock.command.blind',
    'tshock.command.dance',
    'tshock.command.sit',
    'tshock.command.respawn',
    'tshock.command.third',
    'tshock.command.pvp',
    'tshock.command.whisper',
    'tshock.command.w',
    'tshock.command.s',
    'tshock.command.gm',
    'tshock.command.admin',
    'tshock.command.say',
    'tshock.command.broadcast',
    'tshock.command.broadcast.allowcolor',
    'tshock.command.give',
    'tshock.command.heal',
    'tshock.command.godmode',
    'tshock.command.invincible',
    'tshock.command.immunebuff',
    'tshock.command.butcher',
    'tshock.command.butcher.hostile',
    'tshock.command.butcher.friendly',
    'tshock.command.butcher.bosses',
    'tshock.command.time',
    'tshock.command.spawn',
    'tshock.command.spawnmob',
    'tshock.command.spawnboss',
    'tshock.command.kick',
    'tshock.command.ban',
    'tshock.command.unban',
    'tshock.command.mute',
    'tshock.command.unmute',
    'tshock.command.punish',
    'tshock.command.anti-cheat',
    'tshock.command.spectate',
    'tshock.command.tp',
    'tshock.command.tphere',
    'tshock.command.tppos',
    'tshock.command.tpoffline',
    'tshock.command.tpsilent',
    'tshock.command.send',
    'tshock.command.warp',
    'tshock.command.home',
    'tshock.command.sethome',
    'tshock.command.essentials',
    'tshock.command.essentials.firework',
    'tshock.command.essentials.roll',
    'tshock.command.essentials.clear',
    'tshock.command.essentials.sudo',
    'tshock.command.reload',
    'tshock.command.reloadcfg',
    'tshock.command.save',
    'tshock.command.npc',
    'tshock.command.npc.spawn',
    'tshock.command.npc.remove',
    'tshock.command.npc.givename',
    'tshock.command.npc.look',
    'tshock.command.npc.maxspawns',
    'tshock.command.npc.spawnrate',
    'tshock.command.npc.buff',
    'tshock.command.world',
    'tshock.command.world.editspawn',
    'tshock.command.world.movenpc',
    'tshock.command.world.transferteam',
    'tshock.command.world.togglepvp',
    'tshock.command.world.toggleparty',
    'tshock.command.world.toggleexpert',
    'tshock.command.region',
    'tshock.command.region.help',
    'tshock.command.region.define',
    'tshock.command.region.delete',
    'tshock.command.region.setowner',
    'tshock.command.region.info',
    'tshock.command.region.list',
    'tshock.command.region.user',
    'tshock.command.region.allowz',
    'tshock.command.region.flag',
    'tshock.command.chest',
    'tshock.command.chest.protect',
    'tshock.command.chest.removeprotection',
    'tshock.command.chest.info',
    'tshock.command.chest.viewinventory',
    'tshock.command.item',
    'tshock.command.item.spawn',
    'tshock.command.item.give',
    'tshock.command.projectile',
    'tshock.command.tilerow',
    'tshock.command.tilewall',
    'tshock.command.removetile',
    'tshock.command.paint',
    'tshock.command.server',
    'tshock.command.server.maintenance',
    'tshock.command.server.broadcast',
    'tshock.command.server.save',
    'tshock.command.server.reload',
    'tshock.command.server.off',
    'tshock.command.server.restart',
    'tshock.command.server.log',
    'tshock.command.server.auth',
    'tshock.command.server.token',
  ],
};

// 合并所有权限，通配符在前，并去重
export const ALL_PERMISSIONS = Array.from(new Set([
  ...WILDCARD_PERMISSIONS,
  ...TSHOCK_PERMISSIONS.rest,
  ...TSHOCK_PERMISSIONS.general,
]));

export const PERMISSION_DESCRIPTIONS: Record<string, string> = {
  // 通配符权限
  'tshock.*': '【通配符】拥有所有权限，包括 REST API、世界管理、玩家管理等全部功能',
  'tshock.rest.*': '【通配符】拥有所有 REST API 权限，可以通过 API 接口管理服务器',
  'tshock.world.*': '【通配符】拥有所有世界管理权限，包括时间控制、怪物管理、区域管理等',
  'tshock.admin.*': '【通配符】拥有所有管理员权限，包括封禁、踢出、禁言等',
  'tshock.command.*': '【通配符】拥有所有命令执行权限',
  // REST API 权限
  'tshock.rest.bans.manage': 'REST API - 管理封禁名单（添加/移除封禁）',
  'tshock.rest.bans.view': 'REST API - 查看封禁名单',
  'tshock.rest.groups.manage': 'REST API - 管理用户组（创建/修改/删除）',
  'tshock.rest.groups.view': 'REST API - 查看用户组信息',
  'tshock.rest.kick': 'REST API - 踢出玩家',
  'tshock.rest.mute': 'REST API - 禁言玩家',
  'tshock.rest.kill': 'REST API - 杀死玩家',
  'tshock.rest.broadcast': 'REST API - 发送广播消息',
  'tshock.rest.command': 'REST API - 在服务器上执行命令',
  'tshock.rest.cfg': 'REST API - 修改服务器配置',
  'tshock.rest.maintenance': 'REST API - 切换维护模式',
  'tshock.rest.users.manage': 'REST API - 管理用户（添加/修改/删除）',
  'tshock.rest.users.view': 'REST API - 查看用户列表',
  'tshock.rest.users.info': 'REST API - 查看用户详细信息',
  'tshock.rest.butcher': 'REST API - 清理怪物',
  'tshock.rest.causeevents': 'REST API - 触发游戏事件（如血月、日食）',
  // 管理员权限
  'tshock.admin': '基础管理员权限',
  'tshock.admin.noban': '不可被封禁',
  'tshock.admin.nokick': '不可被踢出',
  'tshock.admin.nomute': '不可被禁言',
  'tshock.admin.permanentban': '可以永久封禁玩家',
  'tshock.admin.tempban': '可以临时封禁玩家',
  // 世界权限
  'tshock.world.editspawn': '编辑世界出生点',
  'tshock.world.movenpc': '移动 NPC',
  'tshock.world.time.dawn': '设置时间为黎明',
  'tshock.world.time.dusk': '设置时间为黄昏',
  'tshock.world.time.fullmoon': '设置为满月',
  'tshock.world.time.midnight': '设置时间为午夜',
  'tshock.world.time.noon': '设置时间为正午',
  'tshock.world.time.set': '自定义设置时间',
  'tshock.world.toggleexpert': '切换专家模式',
  'tshock.world.toggleparty': '切换派对模式',
  'tshock.world.togglepvp': '切换 PvP 模式',
  'tshock.world.transferteam': '转移玩家队伍',
  'tshock.world.butcher': '清理所有怪物',
  'tshock.world.butcher.hostile': '清理敌对怪物',
  'tshock.world.butcher.friendly': '清理友好怪物',
  'tshock.world.butcher.bosses': '清理 Boss',
  // 玩家状态权限
  'tshock.godmode': '开启自己的无敌模式',
  'tshock.godmode.other': '为其他玩家开启无敌模式',
  'tshock.heal': '治疗自己',
  'tshock.heal.other': '治疗其他玩家',
  'tshock.invincible': '开启自己的隐形模式',
  'tshock.invincible.other': '为其他玩家开启隐形模式',
  'tshock.immunebuff': '自己免疫 Buff 效果',
  'tshock.immunebuff.other': '让其他玩家免疫 Buff 效果',
  // NPC 权限
  'tshock.npc.buff': '给 NPC 添加 Buff',
  'tshock.npc.spawnboss': '生成 Boss',
  'tshock.npc.spawnmob': '生成怪物',
  'tshock.npc.givename': '给 NPC 命名',
  'tshock.npc.look': '查看 NPC 信息',
  'tshock.npc.remove': '移除 NPC',
  'tshock.npc.maxspawns': '设置最大生成数量',
  'tshock.npc.spawnrate': '设置生成速率',
  // 传送权限
  'tshock.spawn': '传送到出生点',
  'tshock.spawn.other': '传送其他玩家到出生点',
  'tshock.warp': '使用传送点',
  'tshock.warp.allowhide': '允许隐藏传送点',
  'tshock.warp.create': '创建传送点',
  'tshock.warp.delete': '删除传送点',
  'tshock.warp.hidden': '使用隐藏传送点',
  'tshock.warp.list': '查看传送点列表',
  'tshock.warp.other': '传送其他玩家到传送点',
  'tshock.warp.send': '发送传送点',
  'tshock.warp.tp': '直接传送到传送点',
  'tshock.home': '传送回家',
  'tshock.home.set': '设置家的位置',
  'tshock.home.allowmultiple': '允许设置多个家',
  'tshock.home.teleport': '传送到家',
  'tshock.tp': '基础传送权限',
  'tshock.tp.here': '把玩家传送到自己身边',
  'tshock.tp.overrideblocked': '强制传送到受限制区域',
  'tshock.tp.pos': '传送到指定坐标',
  'tshock.tp.silent': '静默传送（不显示消息）',
  'tshock.tp.others': '传送其他玩家',
  // 物品权限
  'tshock.item.spawn': '生成物品',
  'tshock.item.give': '给予物品',
  'tshock.item.give.allowstack': '允许堆叠物品',
  'tshock.ignore.ssc': '忽略 SSC（服务器端角色）限制',
  // 箱子权限
  'tshock.chest': '基础箱子权限',
  'tshock.chest.allowstart': '允许使用初始箱子',
  'tshock.chest.info': '查看箱子信息',
  'tshock.chest.log': '查看箱子操作日志',
  'tshock.chest.protect': '保护箱子',
  'tshock.chest.protect.nostack': '箱子不允许堆叠',
  'tshock.chest.removeprotection': '移除箱子保护',
  'tshock.chest.viewinventory': '查看箱子内物品',
  'tshock.chest.allowall': '允许所有箱子操作',
  // 聊天权限
  'tshock.sawpvp': '查看 PvP 聊天',
  'tshock.sawparty': '查看队伍聊天',
  'tshock.say': '发送聊天消息',
  'tshock.say.color': '使用彩色聊天',
  'tshock.saylogs': '查看聊天日志',
  'tshock.whisper': '发送私语',
  'tshock.whisper.color': '使用彩色私语',
  'tshock.whisper.log': '查看私语日志',
  // 其他管理权限
  'tshock.superadmin': '超级管理员权限',
  'tshock.annoy': '允许骚扰玩家',
  'tshock.antispam.exempt': '免反垃圾消息限制',
  'tshock.ban': '封禁玩家',
  'tshock.ban.view': '查看封禁列表',
  'tshock.kick': '踢出玩家',
  'tshock.mute': '禁言玩家',
  'tshock.log.clear': '清除日志',
  'tshock.log.read': '读取日志',
  'tshock.timeban': '限时封禁',
  'tshock.timeban.view': '查看限时封禁',
  'tshock.summon': '召唤玩家',
  'tshock.summon.allowall': '允许召唤所有玩家',
  'tshock.admin.viewtiles': '查看方块信息',
  // 基础命令权限
  'tshock.essentials': '基础 Essentials 命令',
  'tshock.essentials.firework': '放烟花',
  'tshock.essentials.roll': '掷骰子',
  'tshock.essentials.clear': '清理物品',
  'tshock.essentials.sudo': '以其他玩家身份执行命令',
  'tshock.motd': '查看 MOTD',
  'tshock.motd.allowcolor': '允许彩色 MOTD',
  'tshock.motd.admin': '编辑 MOTD',
  'tshock.rules': '查看规则',
  'tshock.rules.allowcolor': '允许彩色规则',
  'tshock.rules.admin': '编辑规则',
  'tshock.time': '查看时间',
  // 区域权限
  'tshock.region': '基础区域权限',
  'tshock.region.setowner': '设置区域所有者',
  'tshock.region.allowz': '允许区域 Z 轴',
  'tshock.region.allowadminuse': '允许管理员使用区域',
  'tshock.region.adminuser': '区域管理员用户',
  'tshock.region.delete': '删除区域',
  'tshock.region.define': '定义区域',
  'tshock.region.flag.own': '设置自己区域的标志',
  'tshock.region.flag.other': '设置其他区域的标志',
  'tshock.region.info': '查看区域信息',
  'tshock.region.list': '查看区域列表',
  'tshock.region.own': '拥有区域',
  'tshock.region.user': '区域用户',
  // 其他杂项权限
  'tshock.send': '发送消息',
  'tshock.projectile': '发射抛射物',
  'tshock.spectate': '旁观模式',
  'tshock.spectate.other': '旁观其他玩家',
  'tshock.removetile': '移除方块',
  'tshock.removetile.quick': '快速移除方块',
  'tshock.paint': '涂漆方块',
  'tshock.tilerow': '整行放方块',
  'tshock.tilewall': '整墙放方块',
  'tshock.tilewall.quick': '快速放墙',
  'tshock.give.item.byid': '按 ID 给予物品',
  'tshock.give.item.byname': '按名称给予物品',
  'tshock.give.buff.byid': '按 ID 给予 Buff',
  'tshock.give.buff.byname': '按名称给予 Buff',
  // 信息命令
  'tshock.command.help': '命令 - 查看帮助',
  'tshock.command.info': '命令 - 查看服务器信息',
  'tshock.command.rules': '命令 - 查看规则',
  'tshock.command.motd': '命令 - 查看 MOTD',
  'tshock.command.who': '命令 - 查看在线玩家',
  // 互动命令
  'tshock.command.me': '命令 - 动作表情',
  'tshock.command.party': '命令 - 队伍管理',
  'tshock.command.hug': '命令 - 拥抱',
  'tshock.command.shake': '命令 - 握手',
  'tshock.command.slap': '命令 - 扇巴掌',
  'tshock.command.point': '命令 - 指向',
  'tshock.command.grow': '命令 - 变大',
  'tshock.command.tell': '命令 - 告诉（私语）',
  'tshock.command.reply': '命令 - 回复',
  'tshock.command.r': '命令 - 快捷回复',
  'tshock.command.p': '命令 - 队伍聊天',
  'tshock.command.rocket': '命令 - 火箭',
  'tshock.command.angry': '命令 - 愤怒表情',
  'tshock.command.laugh': '命令 - 大笑',
  'tshock.command.cry': '命令 - 哭泣',
  'tshock.command.taunt': '命令 - 嘲讽',
  'tshock.command.kill': '命令 - 自杀',
  'tshock.command.puke': '命令 - 呕吐',
  'tshock.command.confused': '命令 - 困惑',
  'tshock.command.blind': '命令 - 失明',
  'tshock.command.dance': '命令 - 跳舞',
  'tshock.command.sit': '命令 - 坐下',
  'tshock.command.respawn': '命令 - 重生',
  'tshock.command.third': '命令 - 第三人称',
  'tshock.command.pvp': '命令 - 切换 PvP',
  'tshock.command.whisper': '命令 - 私语',
  'tshock.command.w': '命令 - 快捷私语',
  'tshock.command.s': '命令 - 快捷消息',
  // 管理员命令
  'tshock.command.gm': '命令 - 游戏管理员模式',
  'tshock.command.admin': '命令 - 管理员菜单',
  'tshock.command.say': '命令 - 发送公告',
  'tshock.command.broadcast': '命令 - 广播消息',
  'tshock.command.broadcast.allowcolor': '命令 - 彩色广播',
  'tshock.command.give': '命令 - 给予物品',
  'tshock.command.heal': '命令 - 治疗',
  'tshock.command.godmode': '命令 - 无敌模式',
  'tshock.command.invincible': '命令 - 隐形模式',
  'tshock.command.immunebuff': '命令 - 免疫 Buff',
  'tshock.command.butcher': '命令 - 清理怪物',
  'tshock.command.time': '命令 - 设置时间',
  'tshock.command.spawn': '命令 - 传送到出生点',
  'tshock.command.spawnmob': '命令 - 生成怪物',
  'tshock.command.spawnboss': '命令 - 生成 Boss',
  'tshock.command.kick': '命令 - 踢出',
  'tshock.command.ban': '命令 - 封禁',
  'tshock.command.unban': '命令 - 解封',
  'tshock.command.mute': '命令 - 禁言',
  'tshock.command.unmute': '命令 - 解除禁言',
  'tshock.command.punish': '命令 - 惩罚',
  'tshock.command.anti-cheat': '命令 - 反作弊',
  'tshock.command.spectate': '命令 - 旁观',
  'tshock.command.tp': '命令 - 传送',
  'tshock.command.tphere': '命令 - 传送到这里',
  'tshock.command.tppos': '命令 - 传送到坐标',
  'tshock.command.tpoffline': '命令 - 传送离线玩家',
  'tshock.command.tpsilent': '命令 - 静默传送',
  'tshock.command.send': '命令 - 发送消息',
  'tshock.command.warp': '命令 - 传送点',
  'tshock.command.home': '命令 - 回家',
  'tshock.command.sethome': '命令 - 设置家',
  'tshock.command.essentials': '命令 - Essentials',
  'tshock.command.reload': '命令 - 重载配置',
  'tshock.command.reloadcfg': '命令 - 重载配置文件',
  'tshock.command.save': '命令 - 保存世界',
  // NPC 命令
  'tshock.command.npc': '命令 - NPC 管理',
  'tshock.command.npc.spawn': '命令 - 生成 NPC',
  'tshock.command.npc.remove': '命令 - 移除 NPC',
  'tshock.command.npc.givename': '命令 - 给 NPC 命名',
  'tshock.command.npc.look': '命令 - 查看 NPC',
  'tshock.command.npc.maxspawns': '命令 - 最大生成数量',
  'tshock.command.npc.spawnrate': '命令 - 生成速率',
  'tshock.command.npc.buff': '命令 - NPC Buff',
  // 世界命令
  'tshock.command.world': '命令 - 世界管理',
  'tshock.command.world.editspawn': '命令 - 编辑出生点',
  'tshock.command.world.movenpc': '命令 - 移动 NPC',
  'tshock.command.world.transferteam': '命令 - 转移队伍',
  'tshock.command.world.togglepvp': '命令 - 切换 PvP',
  'tshock.command.world.toggleparty': '命令 - 切换派对',
  'tshock.command.world.toggleexpert': '命令 - 切换专家模式',
  // 区域命令
  'tshock.command.region': '命令 - 区域管理',
  'tshock.command.region.help': '命令 - 区域帮助',
  'tshock.command.region.define': '命令 - 定义区域',
  'tshock.command.region.delete': '命令 - 删除区域',
  'tshock.command.region.setowner': '命令 - 设置区域所有者',
  'tshock.command.region.info': '命令 - 区域信息',
  'tshock.command.region.list': '命令 - 区域列表',
  'tshock.command.region.user': '命令 - 区域用户',
  'tshock.command.region.allowz': '命令 - 区域 Z 轴',
  'tshock.command.region.flag': '命令 - 区域标志',
  // 箱子命令
  'tshock.command.chest': '命令 - 箱子管理',
  'tshock.command.chest.protect': '命令 - 保护箱子',
  'tshock.command.chest.removeprotection': '命令 - 移除箱子保护',
  'tshock.command.chest.info': '命令 - 箱子信息',
  'tshock.command.chest.viewinventory': '命令 - 查看箱子物品',
  // 物品命令
  'tshock.command.item': '命令 - 物品管理',
  'tshock.command.item.spawn': '命令 - 生成物品',
  'tshock.command.item.give': '命令 - 给予物品',
  // 建筑命令
  'tshock.command.projectile': '命令 - 抛射物',
  'tshock.command.tilerow': '命令 - 整行方块',
  'tshock.command.tilewall': '命令 - 整墙',
  'tshock.command.removetile': '命令 - 移除方块',
  'tshock.command.paint': '命令 - 涂漆',
  // 服务器命令
  'tshock.command.server': '命令 - 服务器管理',
  'tshock.command.server.maintenance': '命令 - 维护模式',
  'tshock.command.server.broadcast': '命令 - 广播',
  'tshock.command.server.save': '命令 - 保存',
  'tshock.command.server.reload': '命令 - 重载',
  'tshock.command.server.off': '命令 - 关闭服务器',
  'tshock.command.server.restart': '命令 - 重启服务器',
  'tshock.command.server.log': '命令 - 日志',
  'tshock.command.server.auth': '命令 - 认证',
  'tshock.command.server.token': '命令 - Token',
};

export const CATEGORIZED_PERMISSIONS = [
  {
    category: '通配符权限',
    permissions: WILDCARD_PERMISSIONS,
  },
  {
    category: 'REST API 权限',
    permissions: TSHOCK_PERMISSIONS.rest,
  },
  {
    category: '一般管理权限',
    permissions: TSHOCK_PERMISSIONS.general,
  },
] as const;
