export const CONFIG_DESCRIPTIONS: Record<string, string> = {
  // ===== 服务器基础配置 =====
  'ServerName': '服务器名称，显示在玩家客户端的多人游戏列表中',
  'ServerPassword': '服务器密码，玩家加入时需要输入此密码才能进入游戏',
  'Port': '服务器运行端口，默认 7777',
  'ServerPort': '服务器监听的 TCP 端口号，默认 7777',
  'MaxPlayers': '服务器最大玩家数量上限',
  'MaxSlots': '服务器最大玩家数量上限',
  'ReservedSlots': '预留座位数，超过最大玩家数后保留玩家可加入',
  'ServerFullNotice': '当服务器已满时，发送给试图加入的玩家的提示消息',
  'ServerFullReason': '服务器已满时踢出玩家的提示消息',
  'ServerFullNoReservedReason': '服务器已满（包括预留空间）时踢出玩家的提示消息',
  'ServerNamePlate': '显示在玩家头顶的名称标签文字',
  'UseServerName': '是否用 ServerName 替换世界名称',
  'RequireLogin': '是否强制要求玩家登录',
  'RememberLeavePos': '是否记住玩家离开时的位置',
  'MaximumLoginAttempts': '最大登录尝试次数',

  // ===== REST API 配置（必需，锁定） =====
  'RestApiEnabled': '是否启用 REST API 接口。这是 Web 控制台功能的必要条件，必须开启',
  'RestApiPort': 'REST API 服务监听的端口号，默认 7878',
  'EnableTokenEndpointAuthentication': '是否启用 REST API 的身份验证令牌机制，建议开启以确保安全',
  'LogRest': '是否记录所有 REST API 请求到日志文件，便于调试和审计',
  'RESTMaximumRequestsPerInterval': '在指定时间间隔内允许的最大 API 请求数量，超出限制的请求将被拒绝',
  'RESTRequestBucketDecreaseIntervalMinutes': 'API 请求速率限制桶的减少间隔时间（分钟）',
  'ApplicationRestTokens': '存储 REST API 访问令牌的对象，用于身份验证',
  'EnableTokenLoginAuthentication': '是否允许玩家使用 REST API Token 直接登录服务器',
  'EnableRPCEP': '启用 RPC 端点',

  // ===== 游戏模式配置 =====
  'Difficulty': '游戏难度等级：0=普通，1=专家模式，2=大师模式，3=旅途模式',
  'DisableHardmode': '是否禁用困难模式切换，即使世花被插入也不会触发困难模式',
  'ForceXmas': '是否强制启用圣诞节雪景和礼物事件',
  'ForceHalloween': '是否强制启用万圣节南瓜事件',
  'ForceTime': '强制时间设置，"normal" 正常，"day" 白天，"night" 黑夜',

  // ===== 世界与存储配置 =====
  'WorldName': '世界名称，会显示在游戏内',
  'WorldPath': '世界数据文件的存储路径',
  'WorldTileProvider': '世界瓦片提供者类型',
  'BackupPath': '世界备份文件的存储目录路径',
  'LogPath': '服务器日志文件的存储目录路径，默认 "tshock/logs"',
  'StorageType': '数据存储类型，可选 "sqlite"（默认）、"mysql"、"postgres"',
  'SqliteDBPath': 'SQLite 数据库路径',
  'SqliteConnectionString': 'SQLite 连接字符串',
  'MySqlHost': 'MySQL 主机地址和端口，默认 "localhost:3306"',
  'MySqlDbName': 'MySQL 数据库名称',
  'MySqlUsername': 'MySQL 用户名',
  'MySqlPassword': 'MySQL 密码',
  'MySqlConnectionString': 'MySQL 连接字符串',
  'PostgresHost': 'PostgreSQL 主机地址',
  'PostgresDbName': 'PostgreSQL 数据库名称',
  'PostgresUsername': 'PostgreSQL 用户名',
  'PostgresPassword': 'PostgreSQL 密码',
  'PostgresConnectionString': 'PostgreSQL 连接字符串',
  'UseSqlLogs': '是否将日志写入 SQL 数据库而非文件',
  'LogSql': '是否将日志保存到 SQL 数据库',
  'DebugLogs': '是否输出调试日志',
  'DisableSpewLogs': '是否禁用大量日志输出',
  'DisableSecondUpdateLogs': '是否禁用第二次更新的日志',
  'RevertToTextLogsOnSqlFailures': 'SQL 失败时回退到文本日志的次数阈值',

  // ===== 自动保存与备份 =====
  'AutoSave': '是否启用世界自动保存功能',
  'AnnounceSave': '保存世界时是否向所有在线玩家广播通知',
  'SaveWorldOnCrash': '服务器崩溃时是否自动保存当前世界状态',
  'SaveWorldOnLastPlayerExit': '最后一个玩家退出时是否保存世界',
  'ShowBackupAutosaveMessages': '是否在控制台显示自动保存/备份的相关消息',
  'BackupInterval': '世界自动备份的时间间隔（分钟），0 为禁用',
  'BackupKeepFor': '自动备份文件保留的时间（分钟），2880 = 2天',

  // ===== 玩家角色管理 =====
  'ServerSideCharacter': '是否启用服务端角色（SSC）功能，玩家角色数据保存在服务器端',
  'AllowVanillaSSC': '是否允许客户端使用原版的个人世界存储（需服务端 SSC 禁用）',
  'DisableLoginBeforeJoin': '是否允许玩家在不登录的情况下加入服务器',
  'AllowLoginAnyUsername': '允许任意用户名的登录',
  'AllowRegisterAnyUsername': '允许注册任意用户名',
  'MinimumPasswordLength': '最小密码长度',
  'HashAlgorithm': '密码加密算法，可选: sha512, sha256, md5',
  'BCryptWorkFactor': 'BCrypt 加密工作因子',
  'DisableUUIDLogin': '是否禁用 UUID 登录',
  'KickEmptyUUID': '是否踢出 UUID 为空的玩家',
  'DefaultRegistrationGroupName': '新用户注册时的默认用户组',
  'DefaultGuestGroupName': '访客用户组名称',

  // ===== 权限与黑白名单 =====
  'DisableWhitelist': '是否禁用白名单功能，禁用后不在白名单中的玩家也能加入',
  'DisableBlacklist': '是否禁用黑名单功能，禁用后即使在黑名单中的玩家也能加入',
  'EnableWhitelist': '启用白名单',
  'WhitelistKickReason': '白名单踢出消息',
  'EnableIPBans': '启用 IP 地址封禁',
  'DisableDefaultIPBan': '是否禁用默认 IP 封禁',
  'KickProxyUsers': '是否踢出使用代理/VPN 连接的玩家',
  'BanOnHardcoreDeath': '硬核玩家死亡时是否封禁',
  'HardcoreBanReason': '硬核玩家死亡封禁理由',
  'KickOnHardcoreDeath': '硬核玩家死亡时是否踢出',
  'HardcoreKickReason': '硬核玩家死亡踢出理由',
  'BanOnMediumcoreDeath': '中核玩家死亡时是否封禁',
  'MediumcoreBanReason': '中核玩家死亡封禁理由',
  'KickOnMediumcoreDeath': '中核玩家死亡时是否踢出',
  'MediumcoreKickReason': '中核玩家死亡踢出理由',
  'DisableHardcoreBan': '硬核模式玩家死亡后是否自动封禁其 IP',
  'DisableBugs': '是否禁用客户端的 Bug 报告功能',
  'WhitelistSucks': '白名单相关设置',
  'HardcoreOnly': '是否只允许硬核模式玩家加入',
  'MediumcoreOnly': '是否只允许中核模式玩家加入',
  'SoftcoreOnly': '是否只允许软核模式玩家加入',
  'SuppressPermissionFailureNotices': '是否抑制权限失败的提示消息',

  // ===== 建造与破坏 =====
  'DisableBuild': '是否禁用玩家的方块建造和破坏权限（管理员除外）',
  'TilePaintThreshold': '方块粉刷阈值',
  'KickOnTilePaintThresholdBroken': '是否在方块粉刷超过阈值时踢出玩家',
  'TileKillThreshold': '方块破坏阈值',
  'KickOnTileKillThresholdBroken': '是否在方块破坏超过阈值时踢出玩家',
  'TilePlaceThreshold': '方块放置阈值',
  'KickOnTilePlaceThresholdBroken': '是否在方块放置超过阈值时踢出玩家',
  'TileLiquidThreshold': '方块液体阈值',
  'KickOnTileLiquidThresholdBroken': '是否在方块液体超过阈值时踢出玩家',
  'RangeChecks': '是否启用范围检查',
  'MaxRangeForDisabled': '禁用范围的最大距离',
  'AllowCutTilesAndBreakables': '是否允许切割方块和可破坏物',
  'AllowIce': '是否允许冰相关功能',
  'AllowCrimsonCreep': '是否允许猩红蔓延',
  'AllowCorruptionCreep': '是否允许腐化蔓延',
  'AllowHallowCreep': '是否允许神圣蔓延',
  'PreventInvalidPlaceStyle': '是否防止无效的放置样式',

  // ===== 事件与入侵 =====
  'DisableInvasion': '是否禁用所有类型的入侵事件',
  'DisableSnowMoon': '是否禁用霜月事件',
  'DisablePumpkinMoon': '是否禁用南瓜月事件',
  'DisabledInvasions': '禁用的特定入侵事件列表',
  'DisableInvasionsWormholeGreeting': '入侵事件时是否禁用虫洞问候',
  'InvasionMultiplier': '入侵事件敌怪数量倍率',
  'InfiniteInvasion': '是否启用无限入侵',
  'AnonymousBossInvasions': '入侵Boss是否匿名显示',

  // ===== 其他游戏功能 =====
  'DisableDungeonGuardian': '是否禁用地牢守护者（极度强大的Boss，击败可获得世花）',
  'DisableFishing': '是否禁用钓鱼功能',
  'DisableSunMoon': '是否禁用日/月神坛修改时间的功能',
  'DisableClownBombs': '是否禁用小丑的爆炸气球攻击',
  'DisablePrimeBombs': '是否禁用机械骷髅王的炸弹攻击',
  'DisableSnowBalls': '是否禁用雪球的伤害效果',
  'DisableTombstones': '是否禁用墓碑生成',
  'DisableInvisPvP': '是否禁用 PvP 中的隐身效果',
  'DisableModifiedZenith': '是否禁用修改过的天顶剑',
  'DisableCustomDeathMessages': '是否禁用自定义死亡消息',
  'AllowCtTag': '是否允许 Ct 标签',
  'PreventBannedItemSpawn': '是否防止禁用物品的生成',
  'AllowAllowedGroupsToSpawnBannedItems': '是否允许特定用户组生成禁用物品',
  'PreventDeadModification': '是否防止死亡时的修改',
  'GiveItemsDirectly': '是否直接给予物品',
  'IgnoreChestStacksOnLoad': '加载世界时是否忽略宝箱堆叠',
  'IgnoreProjUpdate': '是否忽略投射物更新',
  'IgnoreProjKill': '是否忽略投射物击杀',
  'ProjIgnoreShrapnel': '投射物是否忽略弹片',
  'ProjectileThreshold': '投射物阈值',
  'KickOnProjectileThresholdBroken': '是否在投射物超过阈值时踢出玩家',
  'MaxDamage': '玩家造成的最大伤害限制',
  'MaxProjDamage': '投射物造成的最大伤害限制',
  'KickOnDamageThresholdBroken': '超出伤害阈值时是否踢出玩家',
  'HealOtherThreshold': '治疗他人阈值',
  'KickOnHealOtherThresholdBroken': '是否在治疗他人超过阈值时踢出玩家',
  'BombExplosionRadius': '炸弹爆炸半径',
  'StatueSpawn200': '距离 200 像素内的雕像最大生成数量',
  'StatueSpawn600': '距离 600 像素内的雕像最大生成数量',
  'StatueSpawnWorld': '整个世界的雕像最大生成数量',

  // ===== 玩家出生与保护 =====
  'SpawnProtection': '是否启用出生点保护',
  'SpawnProtectionRadius': '出生点保护半径，防止在出生点保护范围内放置物块',
  'spawnProtectionRadius': '防止在出生点保护范围内放置物块',
  'DefaultMaximumSpawns': '默认最大NPC生成数量',
  'DefaultSpawnRate': '默认敌怪生成速率，数值越低生成越快',
  'RespawnSeconds': '玩家死亡后重生等待时间（秒）',
  'RespawnBossSeconds': 'Boss死亡后重生等待时间（秒）',
  'Respawn': '玩家死亡后是否自动重生',
  'AutoRegen': '是否启用自动生命值和魔力值回复',
  'RatePlayerSave': '玩家数据自动保存速率',
  'MaxHP': '玩家最大生命值上限',
  'MaxMP': '玩家最大魔力值上限',

  // ===== 玩家对战与消耗品 =====
  'PvP': '是否启用玩家间 PvP（玩家对战）',
  'PvPMode': 'PvP 模式："normal" 正常，"always" 总是开启，"disabled" 禁用',
  'RoundsPerAmmo': '每消耗一个弹药物品可以射击的回合数',
  'InfinitePvPConsumables': '玩家在 PvP 模式下是否获得无限弹药',

  // ===== 区域保护 =====
  'RegionProtectChests': '是否保护区域内的宝箱',
  'RegionProtectGemLocks': '是否保护区域内的宝石锁',

  // ===== 聊天配置 =====
  'ChatFormat': '聊天消息格式模板，变量: {0}玩家组，{1}前缀，{2}玩家名，{3}后缀，{4}消息',
  'ChatAboveHeadsFormat': '头顶聊天格式',
  'EnableChatAboveHeads': '是否启用头顶聊天显示',
  'CommandSpecifier': '命令前缀符号，默认 "/"',
  'CommandSilentSpecifier': '静默命令前缀符号，默认 "."',
  'MaximumChatMessageLength': '最大聊天消息长度',
  'TruncateExcessiveChatMessages': '是否截断过长的聊天消息',
  'EnableChatPrepend': '聊天消息是否添加玩家名称前缀',
  'SilencePrefixMode': '是否静默忽略聊天前缀模式',
  'BroadcastRespawns': '是否广播玩家重生消息',
  'SuperAdminChatRGB': '超级管理员聊天颜色 RGB 值数组',
  'SuperAdminChatPrefix': '超级管理员聊天前缀',
  'SuperAdminChatSuffix': '超级管理员聊天后缀',
  'BroadcastRGB': '广播消息颜色 RGB 值数组',

  // ===== 其他 =====
  'MainLandSize': '主世界陆地大小（像素）',
  'evilBorder': '腐化/神圣蔓延的边界大小',
  'BoundsWidth': '世界宽度边界',
  'BoundsHeight': '世界高度边界',
  'LogicalCheckLag': '是否启用逻辑延迟检测',
  'EnableGeoIP': '是否启用基于 IP 地址的地理位置检测',
  'DisplayIPToAdmins': '是否向管理员显示玩家 IP',
  'ServerRegion': '服务器所属地区（用于匹配）',
  'LastAPIUpdateIndex': '最后更新的 API 索引',
  'ChannelPiggyback': 'Piggy 频道负载均衡策略',

  // ===== SSC (Server Side Character) 配置 =====
  'Enabled': '是否启用服务端角色功能（SSC）。启用后玩家角色数据将保存在服务器端，玩家背包会被服务器数据覆盖',
  'ServerSideCharacterSave': '服务器保存角色数据的间隔时间（分钟）。超过此时间未活跃的角色将被自动保存',
  'LogonDiscardThreshold': '玩家登录后超过此时间（秒）未选择角色则丢弃未保存的更改',
  'StartingHealth': '新注册的玩家创建角色时的初始生命值',
  'StartingMana': '新注册的玩家创建角色时的初始魔力值',
  'StartingInventory': '新注册的玩家创建角色时的初始物品列表',
  'KeepPlayerAppearance': '是否保留玩家的外观设置（皮肤、颜色等）',
  'KeepPlayerHomePos': '是否保留玩家的床铺/重生点位置',
  'KeepPlayerRespawnPos': '是否保留玩家的重生点位置',
  'BansSlimes': '硬核死亡后是否封禁',
  'BansPlayers': '硬核死亡后是否封禁玩家',
  'RespawnBoss': 'Boss 战死亡后是否需要等待 Boss 消失才能重生',
  'ShowRespawnTimer': '是否在屏幕上显示重生倒计时',
  'ForceRespawnTime': '强制重生时间（秒）',
  'ForceNonrespawnTime': '强制非重生时间（秒）',
  'RespawnTime': '普通重生时间（秒）',
  'DefaultSpawnX': '默认出生点 X 坐标',
  'DefaultSpawnY': 'Default spawn point Y coordinate',
  'PvPForceOn': '是否强制启用 PvP',
  'SBQC': '是否启用 SBQC (Something Beyond Quick)',
  'SBQCSpawnEnabled': '是否启用 SBQC 生成',
  'KickOnInsufficientPermissions': '权限不足时是否踢出玩家',
  'WarnPlayersAboutBypassPermission': '是否警告玩家绕过权限',
  'ForcePassword': '是否强制要求设置密码',
  'RememberPlayerPosition': '是否记住玩家退出时的位置',
  'LastPlayerPosition': '上次玩家退出时的位置',
  'InventoryBackupMultiplier': '物品栏备份倍数',
  'KeepCoinsAcrossSyncs': '金币是否跨同步保留',
  'DisableUsernamePrefixes': '禁用用户名前缀',
  'StartingBuffMaxTime': '初始增益最大时间',
  'AutoSaveForTestMode': '测试模式下自动保存',
  'HybridDeath_PVP': '混合死亡模式下 PvP 设置',
  'HybridDeath_Kick': '混合死亡模式下是否踢出玩家',
  'HybridDeath_Ban': '混合死亡模式下是否封禁玩家',
  'HybridDeathMode': '混合死亡模式设置',
};
