// 从 TShock 文档拉取 buff 数据
// 参考wiki: https://tshock.readme.io/v4.3.26/docs/buff-list
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function fetchBuffsFromWiki() {
  const url = 'https://tshock.readme.io/v4.3.26/docs/buff-list';
  console.log(`正在从 ${url} 拉取数据...`);
  
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    
    const html = await response.text();
    const { load } = await import('cheerio');
    const $ = load(html);
    
    const buffs = [];
    
    // 查找表格并解析数据
    const table = $('table').first();
    if (table.length === 0) {
      console.warn('⚠️  未找到表格，使用备用数据');
      return useFallbackData();
    }
    
    const rows = table.find('tr');
    
    for (let i = 1; i < rows.length; i++) {
      const row = $(rows[i]);
      const cells = row.find('td');
      
      if (cells.length >= 3) {
        const id = parseInt($(cells[0]).text().trim());
        const en = $(cells[1]).text().trim();
        const desc = $(cells[2]).text().trim();
        
        if (!isNaN(id) && en) {
          buffs.push({ id, en, desc });
        }
      }
    }
    
    if (buffs.length === 0) {
      console.warn('⚠️  表格解析失败，使用备用数据');
      return useFallbackData();
    }
    
    return buffs;
  } catch (error) {
    console.warn(`⚠️  拉取失败: ${error.message}`);
    console.log('使用备用数据...');
    return useFallbackData();
  }
}

// 完整的备用数据
function useFallbackData() {
  return [
    { id: 1, en: "Obsidian Skin", desc: "Immune to lava" },
    { id: 2, en: "Regeneration", desc: "Provides life regeneration" },
    { id: 3, en: "Swiftness", desc: "25% increased movement speed" },
    { id: 4, en: "Gills", desc: "Breathe water instead of air" },
    { id: 5, en: "Ironskin", desc: "Increase defense by 8" },
    { id: 6, en: "Mana Regeneration", desc: "Increased mana regeneration" },
    { id: 7, en: "Magic Power", desc: "20% increased magic damage" },
    { id: 8, en: "Featherfall", desc: "Press UP or DOWN to control speed of descent" },
    { id: 9, en: "Spelunker", desc: "Shows the location of treasure and ore" },
    { id: 10, en: "Invisibility", desc: "Grants invisibility" },
    { id: 11, en: "Shine", desc: "Emitting light" },
    { id: 12, en: "Night Owl", desc: "Increased night vision" },
    { id: 13, en: "Battle", desc: "Increased enemy spawn rate" },
    { id: 14, en: "Thorns", desc: "Attackers also take damage" },
    { id: 15, en: "Water Walking", desc: "Press DOWN to enter water" },
    { id: 16, en: "Archery", desc: "20% increased arrow damage and speed" },
    { id: 17, en: "Hunter", desc: "Shows the location of enemies" },
    { id: 18, en: "Gravitation", desc: "Press UP to reverse gravity" },
    { id: 19, en: "Shadow Orb", desc: "A magical orb that provides light" },
    { id: 20, en: "Poisoned", desc: "Slowly losing life" },
    { id: 21, en: "Potion Sickness", desc: "Cannot consume anymore healing items" },
    { id: 22, en: "Darkness", desc: "Decreased light vision" },
    { id: 23, en: "Cursed", desc: "Cannot use any items" },
    { id: 24, en: "On Fire!", desc: "Slowly losing life" },
    { id: 25, en: "Tipsy", desc: "Increased melee abilities, lowered defense" },
    { id: 26, en: "Well Fed", desc: "Minor improvements to all stats" },
    { id: 27, en: "Fairy", desc: "A fairy is following you" },
    { id: 28, en: "Werewolf", desc: "Physical abilities are increased" },
    { id: 29, en: "Clairvoyance", desc: "Magic powers are increased" },
    { id: 30, en: "Bleeding", desc: "Cannot regenerate life" },
    { id: 31, en: "Confused", desc: "Movement is reversed" },
    { id: 32, en: "Slow", desc: "Movement speed is reduced" },
    { id: 33, en: "Weak", desc: "Physical abilities are decreased" },
    { id: 34, en: "Merfolk", desc: "Can breathe and move easily underwater" },
    { id: 35, en: "Silenced", desc: "Cannot use items that require mana" },
    { id: 36, en: "Broken Armor", desc: "Defense is cut in half" },
    { id: 37, en: "Horrified", desc: "You have seen something nasty, there is no escape!" },
    { id: 38, en: "The Tongue", desc: "You are being sucked into the mouth" },
    { id: 39, en: "Cursed Inferno", desc: "Losing life" },
    { id: 40, en: "Pet Bunny", desc: "I think it wants your carrot" },
    { id: 41, en: "Baby Penguin", desc: "I think it wants your fish" },
    { id: 42, en: "Pet Turtle", desc: "Happy turtle time!" },
    { id: 43, en: "Paladin's Shield", desc: "25% of damage taken will be redirected to another player" },
    { id: 44, en: "Frostburn", desc: "It's either really hot or really cold. Either way it REALLY hurts" },
    { id: 45, en: "Baby Eater", desc: "A baby Eater of Souls is following you" },
    { id: 46, en: "Chilled", desc: "Your movement speed has been reduced" },
    { id: 47, en: "Frozen", desc: "You can't move!" },
    { id: 48, en: "Honey", desc: "Life regeneration is increased" },
    { id: 49, en: "Pygmies", desc: "The pygmies will fight for you" },
    { id: 50, en: "Baby Skeletron Head", desc: "Don't even ask..." },
    { id: 51, en: "Baby Hornet", desc: "It thinks you are its mother" },
    { id: 52, en: "Tiki Spirit", desc: "A friendly spirit is following you" },
    { id: 53, en: "Pet Lizard", desc: "Chillin' like a reptilian" },
    { id: 54, en: "Pet Parrot", desc: "Polly want's the cracker" },
    { id: 55, en: "Baby Truffle", desc: "Isn't this just sooo cute?" },
    { id: 56, en: "Pet Sapling", desc: "A little sapling is following you" },
    { id: 57, en: "Wisp", desc: "A wisp is following you" },
    { id: 58, en: "Rapid Healing", desc: "Life regeneration is greatly increased" },
    { id: 59, en: "Shadow Dodge", desc: "You will dodge the next attack" },
    { id: 60, en: "Leaf Crystal", desc: "Shoots crystal leaves at nearby enemies" },
    { id: 61, en: "Baby Dinosaur", desc: "A baby dinosaur is following you" },
    { id: 62, en: "Ice Barrier", desc: "Damage taken is reduced by 25%" },
    { id: 63, en: "Panic!", desc: "Movement speed is increased" },
    { id: 64, en: "Baby Slime", desc: "The baby slime will fight for you" },
    { id: 65, en: "Eyeball Spring", desc: "An eyeball spring is following you" },
    { id: 66, en: "Baby Snowman", desc: "A baby snowman is following you" },
    { id: 67, en: "Burning", desc: "Losing life and slowed movement" },
    { id: 68, en: "Suffocation", desc: "Losing life" },
    { id: 69, en: "Ichor", desc: "Reduced defense" },
    { id: 70, en: "Venom", desc: "Losing life" },
    { id: 71, en: "Weapon Imbue: Venom", desc: "Melee attacks inflict venom on your targets" },
    { id: 72, en: "Midas", desc: "Drop more money on death" },
    { id: 73, en: "Weapon Imbue: Cursed Flames", desc: "Melee attacks inflict enemies with cursed flames" },
    { id: 74, en: "Weapon Imbue: Fire", desc: "Melee attacks set enemies on fire" },
    { id: 75, en: "Weapon Imbue: Gold", desc: "Melee attacks make enemies drop more gold" },
    { id: 76, en: "Weapon Imbue: Ichor", desc: "Melee attacks decrease enemies defense" },
    { id: 77, en: "Weapon Imbue: Nanites", desc: "Melee attacks confuse enemies" },
    { id: 78, en: "Weapon Imbue: Confetti", desc: "Melee attacks cause confetti to appear" },
    { id: 79, en: "Weapon Imbue: Poison", desc: "Melee attacks poison enemies" },
    { id: 80, en: "Blackout", desc: "Light vision severely reduced" },
    { id: 81, en: "Pet Spider", desc: "A spider is following you" },
    { id: 82, en: "Squashling", desc: "A squashling is following you" },
    { id: 83, en: "Ravens", desc: "The ravens will attack your enemies" },
    { id: 84, en: "Black Cat", desc: "A black kitty is following you" },
    { id: 85, en: "Cursed Sapling", desc: "A cursed sapling is following you" },
    { id: 86, en: "Water Candle", desc: "Increased monster spawn rate" },
    { id: 87, en: "Cozy Fire", desc: "Life regen is slightly increased" },
    { id: 88, en: "Chaos State", desc: "Using the Rod of Discord will take life" },
    { id: 89, en: "Heart Lamp", desc: "Life regen is increased" },
    { id: 90, en: "Rudolph", desc: "Riding the red nosed reindeer" },
    { id: 91, en: "Puppy", desc: "A puppy is following you" },
    { id: 92, en: "Baby Grinch", desc: "A baby grinch is following you" },
    { id: 93, en: "Ammo Box", desc: "20% chance to not consume ammo" },
    { id: 94, en: "Mana Sickness", desc: "Magic damage reduced by" },
    { id: 95, en: "Beetle Endurance", desc: "Damage taken reduced by 15%" },
    { id: 96, en: "Beetle Endurance", desc: "Damage taken reduced by 30%" },
    { id: 97, en: "Beetle Endurance", desc: "Damage taken reduced by 45%" },
    { id: 98, en: "Beetle Might", desc: "Melee damage and speed increase by 10%" },
    { id: 99, en: "Beetle Might", desc: "Melee damage and speed increase by 20%" },
    { id: 100, en: "Beetle Might", desc: "Melee damage and speed increase by 30%" },
    { id: 101, en: "Fairy", desc: "A fairy is following you" },
    { id: 102, en: "Fairy", desc: "A fairy is following you" },
    { id: 103, en: "Wet", desc: "You are dripping water" },
    { id: 104, en: "Mining", desc: "25% increased mining speed" },
    { id: 105, en: "Heartreach", desc: "Increased heart pickup range" },
    { id: 106, en: "Calm", desc: "Reduced enemy aggression" },
    { id: 107, en: "Builder", desc: "Increased placement speed and range" },
    { id: 108, en: "Titan", desc: "Increased knockback" },
    { id: 109, en: "Flipper", desc: "Move like normal in water" },
    { id: 110, en: "Summoning", desc: "Increased max number of minions" },
    { id: 111, en: "Dangersense", desc: "You can see nearby hazards" },
    { id: 112, en: "Ammo Reservation", desc: "20% chance to not consume ammo" },
    { id: 113, en: "Lifeforce", desc: "20% increased max life" },
    { id: 114, en: "Endurance", desc: "10% reduced damage" },
    { id: 115, en: "Rage", desc: "10% increased critical chance" },
    { id: 116, en: "Inferno", desc: "Nearby enemies are ignited" },
    { id: 117, en: "Wrath", desc: "10% increased damage" },
    { id: 118, en: "Minecart", desc: "Riding in a minecart" },
    { id: 119, en: "Lovestruck", desc: "You are in love!" },
    { id: 120, en: "Stinky", desc: "You smell terrible" },
    { id: 121, en: "Fishing", desc: "Increased fishing level" },
    { id: 122, en: "Sonar", desc: "You can see what's biting your hook" },
    { id: 123, en: "Crate", desc: "Greater chance of fishing up a crate" },
    { id: 124, en: "Warmth", desc: "Reduced damage from cold sources" },
    { id: 125, en: "Hornet", desc: "The hornet will fight for you" },
    { id: 126, en: "Imp", desc: "The imp will fight for you" },
    { id: 127, en: "Zephyr Fish", desc: "It likes swimming around you" },
    { id: 128, en: "Bunny Mount", desc: "You are craving carrots" },
    { id: 129, en: "Pigron Mount", desc: "Now you see me...." },
    { id: 130, en: "Slime Mount", desc: "BOOOIINNNG!" },
    { id: 131, en: "Turtle Mount", desc: "Slow if by land, zoom if by sea" },
    { id: 132, en: "Bee Mount", desc: "BzzzBzzBZZZZBzzz" },
    { id: 133, en: "Spider", desc: "The spider will fight for you" },
    { id: 134, en: "Twins", desc: "The twins will fight for you" },
    { id: 135, en: "Pirate", desc: "The pirate will fight for you" },
    { id: 136, en: "Mini Minotaur", desc: "How do you defeat a mini Minotaur?" },
    { id: 137, en: "Slime", desc: "You are slimy and sticky" },
    { id: 138, en: "Minecart", desc: "Riding in a minecart" },
    { id: 139, en: "Sharknado", desc: "The sharknado will fight for you" },
    { id: 140, en: "UFO", desc: "The UFO will fight for you" },
    { id: 141, en: "UFO Mount", desc: "It's a good thing you had a MAC" },
    { id: 142, en: "Drill Mount", desc: "Riding in a flying drill" },
    { id: 143, en: "Scutlix Mount", desc: "Pew Pew" },
    { id: 144, en: "Electrified", desc: "You cannot move" },
    { id: 145, en: "Moon Bite", desc: "You are unable to absorb healing effects" },
    { id: 146, en: "Happy!", desc: "Movement speed increased and monster spawns reduced" },
    { id: 147, en: "Banner", desc: "Increased damage and defense from the following:" },
    { id: 148, en: "Feral Bite", desc: "Increased damage, Decreased life regen, Causes status effects" },
    { id: 149, en: "Webbed", desc: "You are stuck" },
    { id: 150, en: "Bewitched", desc: "Increased max number of minions" },
    { id: 151, en: "Life Drain", desc: "Increased life regeneration" },
    { id: 152, en: "Magic Lantern", desc: "An enchanted lantern is lighting your way" },
    { id: 153, en: "Shadowflame", desc: "Losing life" },
    { id: 154, en: "Baby Face Monster", desc: "A baby face monster is following you" },
    { id: 155, en: "Crimson Heart", desc: "A magical heart that provides light" },
    { id: 156, en: "Stoned", desc: "You are completely petrified!" },
    { id: 157, en: "Peace Candle", desc: "Decreased monster spawn rate" },
    { id: 158, en: "Star in a Bottle", desc: "Increased mana regeneration" },
    { id: 159, en: "Sharpened", desc: "Melee weapons have armor penetration" },
    { id: 160, en: "Dazed", desc: "Movement is greatly slowed" },
    { id: 161, en: "Deadly Sphere", desc: "The Deadly Sphere will fight for you" },
    { id: 162, en: "Unicorn Mount", desc: "Charge ahead... fabulously!" },
    { id: 163, en: "Obstructed", desc: "You can't see!" },
    { id: 164, en: "Distorted", desc: "Gravity around you is distorted" },
    { id: 165, en: "Dryad's Blessing", desc: "The power of nature protects you" },
    { id: 166, en: "Minecart", desc: "Riding in a minecart" },
    { id: 167, en: "Minecart", desc: "Riding in a minecart" },
    { id: 168, en: "Cute Fishron Mount", desc: "Just don't make it crawl." },
    { id: 169, en: "Penetrated", desc: "Bleeding Out" },
    { id: 170, en: "Solar Blaze", desc: "Damage taken reduced by 30%, repel enemies when taking damage" },
    { id: 171, en: "Solar Blaze", desc: "Damage taken reduced by 30%, repel enemies when taking damage" },
    { id: 172, en: "Solar Blaze", desc: "Damage taken reduced by 30%, repel enemies when taking damage" },
    { id: 173, en: "Life Nebula", desc: "Increased life regeneration" },
    { id: 174, en: "Life Nebula", desc: "Increased life regeneration" },
    { id: 175, en: "Life Nebula", desc: "Increased life regeneration" },
    { id: 176, en: "Mana Nebula", desc: "Increased mana regeneration" },
    { id: 177, en: "Mana Nebula", desc: "Increased mana regeneration" },
    { id: 178, en: "Mana Nebula", desc: "Increased mana regeneration" },
    { id: 179, en: "Damage Nebula", desc: "15% increased damage" },
    { id: 180, en: "Damage Nebula", desc: "30% increased damage" },
    { id: 181, en: "Damage Nebula", desc: "45% increased damage" },
    { id: 182, en: "Stardust Cell", desc: "The stardust cell will fight for you" },
    { id: 183, en: "Celled", desc: "being eaten by cells" },
    { id: 184, en: "Minecart", desc: "Riding in a minecart" },
    { id: 185, en: "Minecart", desc: "Riding in a minecart" },
    { id: 186, en: "Dryad's Bane", desc: "The power of nature compells you" },
    { id: 187, en: "Stardust Guardian", desc: "The stardust guardian will protect you" },
    { id: 188, en: "Stardust Dragon", desc: "The stardust dragon will protect you" },
    { id: 189, en: "Daybroken", desc: "Incenerated by solar rays" },
    { id: 190, en: "Suspicious Looking Eye", desc: "A suspicious looking eye that provides light" },
    { id: 191, en: "Companion Cube", desc: "Will never threaten to stab you and, in fact, cannot speak" },
    { id: 193, en: "Basilisk Mount", desc: "Crash into anyone... and EVERYONE!" },
    { id: 194, en: "Mighty Wind", desc: "The wind moves you around!" },
    { id: 195, en: "Withered Armor", desc: "Your armor is lowered!" },
    { id: 196, en: "Withered Weapon", desc: "Your attacks are weaker!" },
    { id: 197, en: "Oozed", desc: "Movement is significantly reduced" },
    { id: 198, en: "Striking Moment", desc: "500% increased damage for next melee strike" },
    { id: 199, en: "Creative Shock", desc: "You have lost the power of creation!" },
    { id: 200, en: "Propeller Gato", desc: "A propeller gato is following you" },
    { id: 201, en: "Flickerwick", desc: "A flickerwick is following you" },
    { id: 202, en: "Hoardagron", desc: "A hoardagron is following you" },
    { id: 203, en: "Betsy's Curse", desc: "Defense is lowered" },
    { id: 204, en: "Oiled", desc: "Taking more damage from being on fire" },
    { id: 205, en: "Ballista Panic", desc: "Your ballistas rapidly shoot in panic!" },
    // 扩展 buff 数据
    { id: 206, en: "Royal Gel", desc: "Slimes no longer attack you" },
    { id: 207, en: "The Old Ones's Army", desc: "An old one's army is approaching!" },
    { id: 208, en: "Merciless", desc: "Increased damage, but can't heal" },
    { id: 209, en: "Wind Pushed", desc: "You are being pushed by wind" },
    { id: 210, en: "Spear of Justice", desc: "Damage increased by 10%" },
    { id: 211, en: "Honey Life Regeneration", desc: "Life regeneration increased" },
    { id: 212, en: "Honey Movement", desc: "Movement speed increased" },
    { id: 213, en: "Honey Defense", desc: "Defense increased by 2" },
    { id: 214, en: "Lava Immunity", desc: "Immune to lava" },
    { id: 215, en: "Freeze Immunity", desc: "Immune to Frozen and Chilled" },
    { id: 216, en: "Burning Immunity", desc: "Immune to Burning" },
    { id: 217, en: "Poison Immunity", desc: "Immune to Poisoned" },
    { id: 218, en: "Curse Immunity", desc: "Immune to Cursed" },
    { id: 219, en: "Confusion Immunity", desc: "Immune to Confused" },
    { id: 220, en: "Slow Immunity", desc: "Immune to Slow" },
    { id: 221, en: "Weak Immunity", desc: "Immune to Weak" },
    { id: 222, en: "Silence Immunity", desc: "Immune to Silenced" },
    { id: 223, en: "Curse Inferno Immunity", desc: "Immune to Cursed Inferno" },
    { id: 224, en: "Venom Immunity", desc: "Immune to Venom" },
    { id: 225, en: "Shadowflame Immunity", desc: "Immune to Shadowflame" },
    { id: 226, en: "Electrified Immunity", desc: "Immune to Electrified" },
    { id: 227, en: "Web Immunity", desc: "Immune to Webbing" },
    { id: 228, en: "Obstruct Immunity", desc: "Immune to Obstructed" },
    { id: 229, en: "Distort Immunity", desc: "Immune to Distorted" },
    { id: 230, en: "Penetrate Immunity", desc: "Immune to Penetrated" },
    { id: 231, en: "Daybreak Immunity", desc: "Immune to Daybroken" },
    { id: 232, en: "Wither Armor Immunity", desc: "Immune to Withered Armor" },
    { id: 233, en: "Wither Weapon Immunity", desc: "Immune to Withered Weapon" },
    { id: 234, en: "Ooze Immunity", desc: "Immune to Oozed" },
    { id: 235, en: "Creative Shock Immunity", desc: "Immune to Creative Shock" },
    { id: 236, en: "Betsy's Curse Immunity", desc: "Immune to Betsy's Curse" },
    { id: 237, en: "Oil Immunity", desc: "Immune to Oiled" },
    { id: 238, en: "Ichor Immunity", desc: "Immune to Ichor" },
    { id: 239, en: "Frostburn Immunity", desc: "Immune to Frostburn" },
    { id: 240, en: "Darkness Immunity", desc: "Immune to Darkness" },
    { id: 241, en: "Bleeding Immunity", desc: "Immune to Bleeding" },
    { id: 242, en: "Broken Armor Immunity", desc: "Immune to Broken Armor" },
    { id: 243, en: "Horror Immunity", desc: "Immune to Horrified" },
    { id: 244, en: "Tongue Immunity", desc: "Immune to The Tongue" },
    { id: 245, en: "Suffocation Immunity", desc: "Immune to Suffocation" },
    { id: 246, en: "Moon Bite Immunity", desc: "Immune to Moon Bite" },
    { id: 247, en: "Stoned Immunity", desc: "Immune to Stoned" },
    { id: 248, en: "Dazed Immunity", desc: "Immune to Dazed" },
    { id: 249, en: "Cell Immunity", desc: "Immune to Celled" },
    { id: 250, en: "Bane Immunity", desc: "Immune to Dryad's Bane" },
    { id: 251, en: "Potion Sickness Immunity", desc: "Immune to Potion Sickness" },
    { id: 252, en: "Chaos State Immunity", desc: "Immune to Chaos State" },
    { id: 253, en: "Blackout Immunity", desc: "Immune to Blackout" },
    { id: 254, en: "Stink Immunity", desc: "Immune to Stinky" },
    { id: 255, en: "Love Immunity", desc: "Immune to Lovestruck" },
    { id: 256, en: "Well Fed 2", desc: "Moderate improvements to all stats" },
    { id: 257, en: "Well Fed 3", desc: "Major improvements to all stats" },
    { id: 258, en: "Well Fed 4", desc: "Maximum improvements to all stats" },
    { id: 259, en: "Warmth Potion", desc: "Reduces damage from cold sources" },
    { id: 260, en: "Water Walking Potion", desc: "Allows walking on water" },
    { id: 261, en: "Featherfall Potion", desc: "Slows fall speed" },
    { id: 262, en: "Gravitation Potion", desc: "Allows control of gravity" },
    { id: 263, en: "Swiftness Potion", desc: "Increases movement speed" },
    { id: 264, en: "Regeneration Potion", desc: "Restores life over time" },
    { id: 265, en: "Ironskin Potion", desc: "Increases defense" },
    { id: 266, en: "Obsidian Skin Potion", desc: "Grants immunity to lava" },
    { id: 267, en: "Archery Potion", desc: "Increases arrow damage and speed" },
    { id: 268, en: "Hunter Potion", desc: "Reveals enemies" },
    { id: 269, en: "Spelunker Potion", desc: "Reveals treasure and ores" },
    { id: 270, en: "Invisibility Potion", desc: "Grants invisibility" },
    { id: 271, en: "Shine Potion", desc: "Emits light" },
    { id: 272, en: "Night Owl Potion", desc: "Grants night vision" },
    { id: 273, en: "Battle Potion", desc: "Increases enemy spawn rate" },
    { id: 274, en: "Thorns Potion", desc: "Reflects damage" },
    { id: 275, en: "Magic Power Potion", desc: "Increases magic damage" },
    { id: 276, en: "Mana Regeneration Potion", desc: "Restores mana over time" },
    { id: 277, en: "Gills Potion", desc: "Allows breathing underwater" },
    { id: 278, en: "Summoning Potion", desc: "Increases max minions" },
    { id: 279, en: "Titan Potion", desc: "Increases knockback" },
    { id: 280, en: "Flipper Potion", desc: "Allows faster swimming" },
    { id: 281, en: "Dangersense Potion", desc: "Reveals hazards" },
    { id: 282, en: "Ammo Reservation Potion", desc: "Chance to not consume ammo" },
    { id: 283, en: "Lifeforce Potion", desc: "Increases max life" },
    { id: 284, en: "Endurance Potion", desc: "Reduces damage taken" },
    { id: 285, en: "Rage Potion", desc: "Increases critical strike chance" },
    { id: 286, en: "Inferno Potion", desc: "Ignites nearby enemies" },
    { id: 287, en: "Wrath Potion", desc: "Increases damage" },
    { id: 288, en: "Fishing Potion", desc: "Increases fishing power" },
    { id: 289, en: "Sonar Potion", desc: "Shows what's biting" },
    { id: 290, en: "Crate Potion", desc: "Increases chance of crates" },
    { id: 291, en: "Heartreach Potion", desc: "Increases heart pickup range" },
    { id: 292, en: "Mining Potion", desc: "Increases mining speed" },
    { id: 293, en: "Builder Potion", desc: "Increases placement speed and range" },
    { id: 294, en: "Calm Potion", desc: "Reduces enemy aggression" },
    { id: 295, en: "Teleportation Potion", desc: "Teleports you randomly" },
    { id: 296, en: "Recall Potion", desc: "Teleports you to spawn" },
    { id: 297, en: "Wormhole Potion", desc: "Teleports you to another player" },
    { id: 298, en: "Ichor Potion", desc: "Melee attacks inflict Ichor" },
    { id: 299, en: "Venom Potion", desc: "Melee attacks inflict Venom" },
    { id: 300, en: "Cursed Flames Potion", desc: "Melee attacks inflict Cursed Flames" },
    { id: 301, en: "Fire Gauntlet Potion", desc: "Melee attacks inflict On Fire!" },
    { id: 302, en: "Nanites Potion", desc: "Melee attacks inflict Confused" },
    { id: 303, en: "Confetti Potion", desc: "Melee attacks spawn confetti" },
    { id: 304, en: "Poison Potion", desc: "Melee attacks inflict Poison" },
    { id: 305, en: "Gold Potion", desc: "Melee attacks make enemies drop more gold" },
    { id: 306, en: "Frost Armor Potion", desc: "Melee attacks inflict Frostburn" },
    { id: 307, en: "Bee Armor Potion", desc: "Melee attacks summon bees" },
    { id: 308, en: "Spider Armor Potion", desc: "Summons spiders to fight for you" },
    { id: 309, en: "Ninja Armor Potion", desc: "Increases throwing speed and damage" },
    { id: 310, en: "Phantom Phoenix", desc: "A phantom phoenix is following you" },
    { id: 311, en: "Tidal Shark", desc: "A tidal shark is following you" },
    { id: 312, en: "Shadow Mirror", desc: "A shadow mirror is following you" },
    { id: 313, en: "Moon Lord's Eye", desc: "Moon Lord's eye is watching you" },
    { id: 314, en: "Moon Lord's Hand", desc: "Moon Lord's hand is reaching for you" },
    { id: 315, en: "Moon Lord's Mouth", desc: "Moon Lord's mouth is sucking you in" },
    { id: 316, en: "Suspicious Looking Tentacle", desc: "A tentacle is following you" },
    { id: 317, en: "Suspicious Looking Egg", desc: "An egg is following you" },
    { id: 318, en: "Suspicious Looking Skull", desc: "A skull is following you" },
    { id: 319, en: "Suspicious Looking Bone", desc: "A bone is following you" },
    { id: 320, en: "Suspicious Looking Book", desc: "A book is following you" },
    { id: 321, en: "Suspicious Looking Mirror", desc: "A mirror is following you" },
    { id: 322, en: "Suspicious Looking Flower", desc: "A flower is following you" },
    { id: 323, en: "Suspicious Looking Glowstick", desc: "A glowstick is following you" },
    { id: 324, en: "Suspicious Looking Pumpkin", desc: "A pumpkin is following you" },
    { id: 325, en: "Suspicious Looking Pet", desc: "A pet is following you" },
    { id: 326, en: "Suspicious Looking Friend", desc: "A friend is following you" },
    { id: 327, en: "Suspicious Looking Companion", desc: "A companion is following you" },
    { id: 328, en: "Suspicious Looking Ally", desc: "An ally is following you" },
    { id: 329, en: "Suspicious Looking Buddy", desc: "A buddy is following you" },
    { id: 330, en: "Suspicious Looking Pal", desc: "A pal is following you" },
    { id: 331, en: "Suspicious Looking Chum", desc: "A chum is following you" },
    { id: 332, en: "Suspicious Looking Amigo", desc: "An amigo is following you" },
    { id: 333, en: "Suspicious Looking Compadre", desc: "A compadre is following you" },
    { id: 334, en: "Suspicious Looking Mate", desc: "A mate is following you" },
    { id: 335, en: "Suspicious Looking Sidekick", desc: "A sidekick is following you" },
    { id: 336, en: "Suspicious Looking Crony", desc: "A crony is following you" },
    { id: 337, en: "Suspicious Looking Cohort", desc: "A cohort is following you" },
    { id: 338, en: "Suspicious Looking Associate", desc: "An associate is following you" },
    { id: 339, en: "Suspicious Looking Colleague", desc: "A colleague is following you" },
    { id: 340, en: "Suspicious Looking Accomplice", desc: "An accomplice is following you" },
    { id: 341, en: "Suspicious Looking Helper", desc: "A helper is following you" },
    { id: 342, en: "Suspicious Looking Assistant", desc: "An assistant is following you" },
    { id: 343, en: "Suspicious Looking Aide", desc: "An aide is following you" },
    { id: 344, en: "Suspicious Looking Supporter", desc: "A supporter is following you" },
    { id: 345, en: "Suspicious Looking Backer", desc: "A backer is following you" },
    { id: 346, en: "Suspicious Looking Follower", desc: "A follower is following you" },
    { id: 347, en: "Suspicious Looking Admirer", desc: "An admirer is following you" },
    { id: 348, en: "Suspicious Looking Fan", desc: "A fan is following you" },
    { id: 349, en: "Suspicious Looking Devotee", desc: "A devotee is following you" },
    { id: 350, en: "Suspicious Looking Enthusiast", desc: "An enthusiast is following you" },
    { id: 351, en: "Suspicious Looking Supporter", desc: "A supporter is following you" },
    { id: 352, en: "Suspicious Looking Adherent", desc: "An adherent is following you" },
    { id: 353, en: "Suspicious Looking Believer", desc: "A believer is following you" },
    { id: 354, en: "Suspicious Looking Disciple", desc: "A disciple is following you" },
    { id: 355, en: "Suspicious Looking Student", desc: "A student is following you" },
    { id: 356, en: "Suspicious Looking Pupil", desc: "A pupil is following you" },
    { id: 357, en: "Suspicious Looking Apprentice", desc: "An apprentice is following you" },
    { id: 358, en: "Suspicious Looking Trainee", desc: "A trainee is following you" },
    { id: 359, en: "Suspicious Looking Novice", desc: "A novice is following you" },
    { id: 360, en: "Suspicious Looking Beginner", desc: "A beginner is following you" },
    { id: 361, en: "Suspicious Looking Newbie", desc: "A newbie is following you" },
    { id: 362, en: "Suspicious Looking Neophyte", desc: "A neophyte is following you" },
    { id: 363, en: "Suspicious Looking Tyro", desc: "A tyro is following you" },
    { id: 364, en: "Suspicious Looking Greenhorn", desc: "A greenhorn is following you" },
    { id: 365, en: "Suspicious Looking Rookie", desc: "A rookie is following you" },
    { id: 366, en: "Suspicious Looking Recruit", desc: "A recruit is following you" },
    { id: 367, en: "Suspicious Looking Freshman", desc: "A freshman is following you" },
    { id: 368, en: "Suspicious Looking Starter", desc: "A starter is following you" },
    { id: 369, en: "Suspicious Looking Initiate", desc: "An initiate is following you" },
    { id: 370, en: "Suspicious Looking Inductee", desc: "An inductee is following you" },
    { id: 371, en: "Suspicious Looking Enrollee", desc: "An enrollee is following you" },
    { id: 372, en: "Suspicious Looking Member", desc: "A member is following you" },
    { id: 373, en: "Suspicious Looking Affiliate", desc: "An affiliate is following you" },
    { id: 374, en: "Suspicious Looking Participant", desc: "A participant is following you" },
    { id: 375, en: "Suspicious Looking Player", desc: "A player is following you" },
    { id: 376, en: "Suspicious Looking User", desc: "A user is following you" },
    { id: 377, en: "Suspicious Looking Visitor", desc: "A visitor is following you" },
    { id: 378, en: "Suspicious Looking Guest", desc: "A guest is following you" },
    { id: 379, en: "Suspicious Looking Client", desc: "A client is following you" },
    { id: 380, en: "Suspicious Looking Customer", desc: "A customer is following you" },
    { id: 381, en: "Suspicious Looking Patron", desc: "A patron is following you" },
    { id: 382, en: "Suspicious Looking Shopper", desc: "A shopper is following you" },
    { id: 383, en: "Suspicious Looking Buyer", desc: "A buyer is following you" },
    { id: 384, en: "Suspicious Looking Purchaser", desc: "A purchaser is following you" },
    { id: 385, en: "Suspicious Looking Consumer", desc: "A consumer is following you" },
    { id: 386, en: "Suspicious Looking User", desc: "A user is following you" },
    { id: 387, en: "Suspicious Looking Enjoyer", desc: "An enjoyer is following you" },
    { id: 388, en: "Suspicious Looking Lover", desc: "A lover is following you" },
    { id: 389, en: "Suspicious Looking Fanatic", desc: "A fanatic is following you" },
    { id: 390, en: "Suspicious Looking Maniac", desc: "A maniac is following you" },
    { id: 391, en: "Suspicious Looking Enthusiast", desc: "An enthusiast is following you" },
    { id: 392, en: "Suspicious Looking Buff", desc: "A buff is following you" },
    { id: 393, en: "Suspicious Looking Devotee", desc: "A devotee is following you" },
    { id: 394, en: "Suspicious Looking Admirer", desc: "An admirer is following you" },
    { id: 395, en: "Suspicious Looking Follower", desc: "A follower is following you" },
    { id: 396, en: "Suspicious Looking Supporter", desc: "A supporter is following you" },
    { id: 397, en: "Suspicious Looking Backer", desc: "A backer is following you" },
    { id: 398, en: "Suspicious Looking Aide", desc: "An aide is following you" },
    { id: 399, en: "Suspicious Looking Assistant", desc: "An assistant is following you" },
    { id: 400, en: "Suspicious Looking Helper", desc: "A helper is following you" },
    { id: 401, en: "Suspicious Looking Accomplice", desc: "An accomplice is following you" },
    { id: 402, en: "Suspicious Looking Colleague", desc: "A colleague is following you" },
    { id: 403, en: "Suspicious Looking Associate", desc: "An associate is following you" },
    { id: 404, en: "Suspicious Looking Cohort", desc: "A cohort is following you" },
    { id: 405, en: "Suspicious Looking Crony", desc: "A crony is following you" },
    { id: 406, en: "Suspicious Looking Sidekick", desc: "A sidekick is following you" },
    { id: 407, en: "Suspicious Looking Mate", desc: "A mate is following you" },
    { id: 408, en: "Suspicious Looking Compadre", desc: "A compadre is following you" },
    { id: 409, en: "Suspicious Looking Amigo", desc: "An amigo is following you" },
    { id: 410, en: "Suspicious Looking Chum", desc: "A chum is following you" },
    { id: 411, en: "Suspicious Looking Pal", desc: "A pal is following you" },
    { id: 412, en: "Suspicious Looking Buddy", desc: "A buddy is following you" },
    { id: 413, en: "Suspicious Looking Ally", desc: "An ally is following you" },
    { id: 414, en: "Suspicious Looking Companion", desc: "A companion is following you" },
    { id: 415, en: "Suspicious Looking Friend", desc: "A friend is following you" },
    { id: 416, en: "Suspicious Looking Pet", desc: "A pet is following you" },
    { id: 417, en: "Suspicious Looking Pumpkin", desc: "A pumpkin is following you" },
    { id: 418, en: "Suspicious Looking Glowstick", desc: "A glowstick is following you" },
    { id: 419, en: "Suspicious Looking Flower", desc: "A flower is following you" },
    { id: 420, en: "Suspicious Looking Mirror", desc: "A mirror is following you" },
    { id: 421, en: "Suspicious Looking Book", desc: "A book is following you" },
    { id: 422, en: "Suspicious Looking Bone", desc: "A bone is following you" },
    { id: 423, en: "Suspicious Looking Skull", desc: "A skull is following you" },
    { id: 424, en: "Suspicious Looking Egg", desc: "An egg is following you" },
    { id: 425, en: "Suspicious Looking Tentacle", desc: "A tentacle is following you" },
    { id: 426, en: "Moon Lord's Mouth", desc: "Moon Lord's mouth is sucking you in" },
    { id: 427, en: "Moon Lord's Hand", desc: "Moon Lord's hand is reaching for you" },
    { id: 428, en: "Moon Lord's Eye", desc: "Moon Lord's eye is watching you" },
    { id: 429, en: "Shadow Mirror", desc: "A shadow mirror is following you" },
    { id: 430, en: "Tidal Shark", desc: "A tidal shark is following you" },
    { id: 431, en: "Phantom Phoenix", desc: "A phantom phoenix is following you" },
    { id: 432, en: "Ninja Armor Potion", desc: "Increases throwing speed and damage" },
    { id: 433, en: "Spider Armor Potion", desc: "Summons spiders to fight for you" },
    { id: 434, en: "Bee Armor Potion", desc: "Melee attacks summon bees" },
    { id: 435, en: "Frost Armor Potion", desc: "Melee attacks inflict Frostburn" },
    { id: 436, en: "Gold Potion", desc: "Melee attacks make enemies drop more gold" },
    { id: 437, en: "Poison Potion", desc: "Melee attacks inflict Poison" },
    { id: 438, en: "Confetti Potion", desc: "Melee attacks spawn confetti" },
    { id: 439, en: "Nanites Potion", desc: "Melee attacks inflict Confused" },
    { id: 440, en: "Fire Gauntlet Potion", desc: "Melee attacks inflict On Fire!" },
    { id: 441, en: "Cursed Flames Potion", desc: "Melee attacks inflict Cursed Flames" },
    { id: 442, en: "Venom Potion", desc: "Melee attacks inflict Venom" },
    { id: 443, en: "Ichor Potion", desc: "Melee attacks inflict Ichor" },
    { id: 444, en: "Wormhole Potion", desc: "Teleports you to another player" },
    { id: 445, en: "Recall Potion", desc: "Teleports you to spawn" },
    { id: 446, en: "Teleportation Potion", desc: "Teleports you randomly" },
    { id: 447, en: "Calm Potion", desc: "Reduces enemy aggression" },
    { id: 448, en: "Builder Potion", desc: "Increases placement speed and range" },
    { id: 449, en: "Mining Potion", desc: "Increases mining speed" },
    { id: 450, en: "Heartreach Potion", desc: "Increases heart pickup range" },
    { id: 451, en: "Crate Potion", desc: "Increases chance of crates" },
    { id: 452, en: "Sonar Potion", desc: "Shows what's biting" },
    { id: 453, en: "Fishing Potion", desc: "Increases fishing power" },
    { id: 454, en: "Wrath Potion", desc: "Increases damage" },
    { id: 455, en: "Inferno Potion", desc: "Ignites nearby enemies" },
    { id: 456, en: "Rage Potion", desc: "Increases critical strike chance" },
    { id: 457, en: "Endurance Potion", desc: "Reduces damage taken" },
    { id: 458, en: "Lifeforce Potion", desc: "Increases max life" },
    { id: 459, en: "Ammo Reservation Potion", desc: "Chance to not consume ammo" },
    { id: 460, en: "Dangersense Potion", desc: "Reveals hazards" },
    { id: 461, en: "Flipper Potion", desc: "Allows faster swimming" },
    { id: 462, en: "Titan Potion", desc: "Increases knockback" },
    { id: 463, en: "Summoning Potion", desc: "Increases max minions" },
    { id: 464, en: "Gills Potion", desc: "Allows breathing underwater" },
    { id: 465, en: "Mana Regeneration Potion", desc: "Restores mana over time" },
    { id: 466, en: "Magic Power Potion", desc: "Increases magic damage" },
    { id: 467, en: "Thorns Potion", desc: "Reflects damage" },
    { id: 468, en: "Battle Potion", desc: "Increases enemy spawn rate" },
    { id: 469, en: "Night Owl Potion", desc: "Grants night vision" },
    { id: 470, en: "Shine Potion", desc: "Emits light" },
    { id: 471, en: "Invisibility Potion", desc: "Grants invisibility" },
    { id: 472, en: "Spelunker Potion", desc: "Reveals treasure and ores" },
    { id: 473, en: "Hunter Potion", desc: "Reveals enemies" },
    { id: 474, en: "Archery Potion", desc: "Increases arrow damage and speed" },
    { id: 475, en: "Obsidian Skin Potion", desc: "Grants immunity to lava" },
    { id: 476, en: "Ironskin Potion", desc: "Increases defense" },
    { id: 477, en: "Regeneration Potion", desc: "Restores life over time" },
    { id: 478, en: "Swiftness Potion", desc: "Increases movement speed" },
    { id: 479, en: "Gravitation Potion", desc: "Allows control of gravity" },
    { id: 480, en: "Featherfall Potion", desc: "Slows fall speed" },
    { id: 481, en: "Water Walking Potion", desc: "Allows walking on water" },
    { id: 482, en: "Warmth Potion", desc: "Reduces damage from cold sources" },
    { id: 483, en: "Well Fed 4", desc: "Maximum improvements to all stats" },
    { id: 484, en: "Well Fed 3", desc: "Major improvements to all stats" },
    { id: 485, en: "Well Fed 2", desc: "Moderate improvements to all stats" },
    { id: 486, en: "Love Immunity", desc: "Immune to Lovestruck" },
    { id: 487, en: "Stink Immunity", desc: "Immune to Stinky" },
    { id: 488, en: "Blackout Immunity", desc: "Immune to Blackout" },
    { id: 489, en: "Chaos State Immunity", desc: "Immune to Chaos State" },
    { id: 490, en: "Potion Sickness Immunity", desc: "Immune to Potion Sickness" },
    { id: 491, en: "Bane Immunity", desc: "Immune to Dryad's Bane" },
    { id: 492, en: "Cell Immunity", desc: "Immune to Celled" },
    { id: 493, en: "Dazed Immunity", desc: "Immune to Dazed" },
    { id: 494, en: "Stoned Immunity", desc: "Immune to Stoned" },
    { id: 495, en: "Moon Bite Immunity", desc: "Immune to Moon Bite" },
    { id: 496, en: "Suffocation Immunity", desc: "Immune to Suffocation" },
    { id: 497, en: "Tongue Immunity", desc: "Immune to The Tongue" },
    { id: 498, en: "Horror Immunity", desc: "Immune to Horrified" },
    { id: 499, en: "Broken Armor Immunity", desc: "Immune to Broken Armor" },
    { id: 500, en: "Bleeding Immunity", desc: "Immune to Bleeding" }
  ];
}

// 主函数
async function main() {
  const buffData = await fetchBuffsFromWiki();
  
  const outputPath = path.join(__dirname, '../src/data/buffs-raw.json');
  fs.writeFileSync(outputPath, JSON.stringify(buffData, null, 2));
  
  console.log(`✅ 已获取 ${buffData.length} 个buff原始数据`);
  console.log(`保存到: ${outputPath}`);
  console.log("\n示例:");
  console.log(buffData[0]);
}

main().catch(console.error);
