name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-electron-win:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Electron for Windows
        run: npm run electron:build:win:zip

      - name: Upload Electron artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-win
          path: release/

  release:
    needs: build-electron-win
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: List artifacts
        run: ls -la

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            electron-win/TShock Controller-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
